spring.application.name=product-service

# spring.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin

spring.mongodb.host=localhost
spring.mongodb.port=27018
spring.mongodb.database=product-service
spring.mongodb.username=root
spring.mongodb.password=password
spring.mongodb.authentication-database=admin